// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Types */
export type AppConfig = { theme: string };

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	testChannel: (onEvent: Channel<string>) => __TAURI_INVOKE<void>("test_channel", { onEvent }),
	getConfig: () => typedError<AppConfig, string>(__TAURI_INVOKE("get_config")),
	setConfig: (config: AppConfig) => typedError<null, string>(__TAURI_INVOKE("set_config", { config })),
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
